services:
  app:
    build: .
    env_file:
      .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/create.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./data/insert.sql:/docker-entrypoint-initdb.d/1_init.sql